# Maki template version: 1.0

version: '3.2'

networks:
  shag:
    external:
      name: shag

services:
  frontend:
    container_name: shag-0924-frontend
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - shag
    depends_on:
      - backend
    ports:
      - 8011:80

  backend:
    container_name: shag-0924-backend
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - shag
    depends_on:
      - cache
      - db

  cache:
    container_name: shag-0924-cache
    image: memcached:1.5-alpine
    networks:
      - shag

  db:
    container_name: shag-0924-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    networks:
      - shag
#    volumes:
#    - db_volume:/var/lib/mysql/data
#
#volumes:
#  db_volume:
#    driver: local

