<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtvQQzI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtvQQzI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtvQQzI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtvQQzI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtvQQzI\App_KernelDevDebugContainer([
    'container.build_hash' => 'AtvQQzI',
    'container.build_id' => '001e2989',
    'container.build_time' => 1601387920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtvQQzI');
